INSERT INTO genres (title) values ('Indie')
INSERT INTO genres (title) values ('Trance')
INSERT INTO genres (title) values ('Alternative Metal')
INSERT INTO genres (title) values ('House')
INSERT INTO genres (title) values ('Электроника')

INSERT INTO singers (name) values ('Spaceouters')
INSERT INTO genres_singers  (genre_id, artist_id) values (2, 1)
INSERT INTO singers (name) values ('Project Blue Sun')
INSERT INTO genres_singers  (genre_id, artist_id) values (4, 2)
INSERT INTO singers (name) values ('The xx')
INSERT INTO genres_singers  (genre_id, artist_id) values (1, 3)
INSERT INTO singers (name) values ('Moby')
INSERT INTO genres_singers  (genre_id, artist_id) values (5, 4)
INSERT INTO singers (name) values ('Dash Berlin')
INSERT INTO genres_singers  (genre_id, artist_id) values (2, 5)
INSERT INTO singers (name) values ('Apocalyptica')
INSERT INTO genres_singers  (genre_id, artist_id) values (3, 6)
INSERT INTO singers (name) values ('ATB')
INSERT INTO genres_singers  (genre_id, artist_id) values (2, 7)
INSERT INTO singers (name) values ('Dani Corbalan')
INSERT INTO genres_singers  (genre_id, artist_id) values (4, 8)
INSERT INTO singers (name) values ('Jellis')
INSERT INTO genres_singers  (genre_id, artist_id) values (5, 9)
INSERT INTO singers (name) values ('Subsets')
INSERT INTO genres_singers  (genre_id, artist_id) values (5, 10)

INSERT INTO albums (title, release_year) values ('Future Memories', 2009)
INSERT INTO singers_albums  (artist_id, album_id) values (7, 1)
INSERT INTO songs (title, duration_sec, album_id) values ('Future Memories', 358, 1)
INSERT INTO collections (title, release_year) values ('Collection 2009', 2009)
INSERT INTO collection_songs (collection_id, song_id) values (1, 1)

INSERT INTO albums (title, release_year) values ('I See You', 2017)
INSERT INTO singers_albums  (artist_id, album_id) values (3, 2)
INSERT INTO songs (title, duration_sec, album_id) values ('Replica', 256, 2)
INSERT INTO collections (title, release_year) values ('Collection 2017', 2017)
INSERT INTO collection_songs (collection_id, song_id) values (2, 2)

INSERT INTO albums (title, release_year) values ('Destroyed', 2011)
INSERT INTO singers_albums  (artist_id, album_id) values (4, 3)
INSERT INTO songs (title, duration_sec, album_id) values ('The Broken Places', 256, 3)
INSERT INTO collections (title, release_year) values ('Collection 2011', 2011)
INSERT INTO collection_songs (collection_id, song_id) values (3, 3)

INSERT INTO albums (title, release_year) values ('Coexist', 2012)
INSERT INTO singers_albums  (artist_id, album_id) values (3, 4)
INSERT INTO songs (title, duration_sec, album_id) values ('Unfold', 182, 4)
INSERT INTO collections (title, release_year) values ('Collection 2012', 2012)
INSERT INTO collection_songs (collection_id, song_id) values (4, 4)

INSERT INTO albums (title, release_year) values ('Home At Last', 2022)
INSERT INTO singers_albums  (artist_id, album_id) values (5, 5)
INSERT INTO songs (title, duration_sec, album_id) values ('Home At Last', 196, 5)
INSERT INTO collections (title, release_year) values ('Collection 2022', 2022)
INSERT INTO collection_songs (collection_id, song_id) values (5, 5)

INSERT INTO albums (title, release_year) values ('Shadowmaker', 2015)
INSERT INTO singers_albums  (artist_id, album_id) values (6, 6)
INSERT INTO songs (title, duration_sec, album_id) values ('Cold Blood', 207, 6)
INSERT INTO collections (title, release_year) values ('Collection 2015', 2015)
INSERT INTO collection_songs (collection_id, song_id) values (6, 6)

INSERT INTO albums (title, release_year) values ('Fireflies', 2018)
INSERT INTO singers_albums  (artist_id, album_id) values (1, 7)
INSERT INTO songs (title, duration_sec, album_id) values ('Fireflies', 298, 7)
INSERT INTO collections (title, release_year) values ('Collection 2018', 2018)
INSERT INTO collection_songs (collection_id, song_id) values (7, 7)

INSERT INTO albums (title, release_year) values ('Life Choice', 2018)
INSERT INTO singers_albums  (artist_id, album_id) values (1, 8)
INSERT INTO songs (title, duration_sec, album_id) values ('Life Choice', 343, 8)
INSERT INTO collection_songs (collection_id, song_id) values (7, 8)

INSERT INTO albums (title, release_year) values ('Life Choice', 2018)
INSERT INTO singers_albums  (artist_id, album_id) values (1, 8)
INSERT INTO songs (title, duration_sec, album_id) values ('Life Choice', 343, 8)
INSERT INTO collection_songs (collection_id, song_id) values (7, 8)

INSERT INTO albums (title, release_year) values ('Foreshadow', 2019)
INSERT INTO singers_albums  (artist_id, album_id) values (1, 9)
INSERT INTO songs (title, duration_sec, album_id) values ('Foreshadow', 304, 9)
INSERT INTO collections (title, release_year) values ('Collection 2019', 2019)
INSERT INTO collection_songs (collection_id, song_id) values (8, 9)

INSERT INTO albums (title, release_year) values ('Better Than Us', 2019)
INSERT INTO singers_albums  (artist_id, album_id) values (2, 10)
INSERT INTO songs (title, duration_sec, album_id) values (' Better Than Us (Deep Mix)', 280, 10)
INSERT INTO collections (title, release_year) values ('Collection 2020', 2020)
INSERT INTO collection_songs (collection_id, song_id) values (9, 10)

INSERT INTO songs (title, duration_sec, album_id) values (' Better Than Us (Radio Edit)', 225, 10)
INSERT INTO collection_songs (collection_id, song_id) values (9, 11)

INSERT INTO albums (title, release_year) values ('Album 2018', 2018)
INSERT INTO singers_albums  (artist_id, album_id) values (8, 11)
INSERT INTO songs (title, duration_sec, album_id) values ('Sorry', 265, 11)
INSERT INTO collection_songs (collection_id, song_id) values (7, 12)

INSERT INTO albums (title, release_year) values ('My Mind', 2019)
INSERT INTO singers_albums  (artist_id, album_id) values (9, 12)
INSERT INTO singers_albums  (artist_id, album_id) values (10, 12)
INSERT INTO songs (title, duration_sec, album_id) values ('My Mind', 204, 13)
INSERT INTO collection_songs (collection_id, song_id) values (9, 12)

INSERT INTO albums (title, release_year) values ('XX', 2009)
INSERT INTO singers_albums  (artist_id, album_id) values (3, 13)
INSERT INTO songs (title, duration_sec, album_id) values ('Intro', 187, 13)
INSERT INTO collection_songs (collection_id, song_id) values (1, 14)
INSERT INTO songs (title, duration_sec, album_id) values ('Infinity', 313, 13)
INSERT INTO collection_songs (collection_id, song_id) values (1, 15)