INSERT INTO genres (title) values ('Indie')
INSERT INTO genres (title) values ('Trance')
INSERT INTO genres (title) values ('Alternative Metal')
INSERT INTO genres (title) values ('Deep House')
INSERT INTO genres (title) values ('Электроника')

INSERT INTO singers (name) values ('Armin Van Buuren')
INSERT INTO genres_singers  (genre_id, artist_id) values (2, 1)
INSERT INTO singers (name) values ('Schiller')
INSERT INTO genres_singers  (genre_id, artist_id) values (5, 2)
INSERT INTO singers (name) values ('The xx')
INSERT INTO genres_singers  (genre_id, artist_id) values (1, 3)
INSERT INTO singers (name) values ('Moby')
INSERT INTO genres_singers  (genre_id, artist_id) values (5, 4)
INSERT INTO singers (name) values ('Dash Berlin')
INSERT INTO genres_singers  (genre_id, artist_id) values (2, 5)
INSERT INTO singers (name) values ('Apocalyptica')
INSERT INTO genres_singers  (genre_id, artist_id) values (3, 6)
INSERT INTO singers (name) values ('ATB')
INSERT INTO genres_singers  (genre_id, artist_id) values (2, 7)

INSERT INTO albums (title, release_year) values ('Future Memories', 2009)
INSERT INTO singers_albums  (artist_id, album_id) values (7, 1)
INSERT INTO songs (title, duration_sec, album_id) values ('Future Memories', 358, 1)
INSERT INTO collections (title, release_year) values ('Collection 2009', 2009)
INSERT INTO collection_songs (collection_id, song_id) values (1, 1)